language: node_js
node_js:
- "stable"
cache:
  directories:
  - node_modules
script:
- npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: docs/.vuepress/dist
  target-branch: master
  on:
    branch: generate